@startuml
left to right direction

class org.tecty.gateway.GatewayApplication {
+ {static} void main(String[])
}
class org.tecty.gateway.security.config.GatewayCorsConfiguration {
+ CorsWebFilter corsWebFilter()
}
class org.tecty.gateway.GatewayApplicationTests {
~ void contextLoads()
}
class org.tecty.gateway.security.config.WebSecurityConfig {
+ SecurityWebFilterChain webFluxSecurityFilterChain(ServerHttpSecurity)
}
@enduml