spring:
  cloud:
    gateway:
      routes:
        - id: uua-service-OAuth
          uri: lb://uaa-service
          predicates:
            - Path=/api/oauth/**
        - id: uua-service-Auth
          uri: lb://uaa-service
          predicates:
            - Path=/api/auth/**
        - id: user-resource
          uri: lb://user-resource
          predicates:
            - Path=/api/res/user/**
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/api/res/storage/**