spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/api/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id: graphql-service
          uri: lb://graphql-service
          predicates:
            - Path=/graphql
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/uua/api/**
          filters:
            - RewritePath=/uua/(?<segment>.*), /$\{segment}
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/api/**
          filters:
            - RewritePath=/inventory/(?<segment>.*), /$\{segment}
        - id: warehouse-service
          uri: lb://warehouse-service
          predicates:
            - Path=/warehouse/api/**
          filters:
            - RewritePath=/warehouse/(?<segment>.*), /$\{segment}
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/coupon/api/**
          filters:
            - RewritePath=/coupon/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/api/**
          filters:
            - RewritePath=/order/(?<segment>.*), /$\{segment}