spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/api/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id: graphql-service
          uri: lb://graphql-service
          predicates:
            - Path=/graphql
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/uua/api/**
          filters:
            - RewritePath=/uua/(?<segment>.*), /$\{segment}